### ISSUE TITLE
Legend sometimes doesn't show up in live example

### ISSUE THREAD

**Issue by tomwayson** [davetimmins/arcgis-react-redux-legend#3]
When I go to https://davetimmins.com/arcgis-react-redux-legend/ sometimes I see: 

![image](https://cloud.githubusercontent.com/assets/662944/22852200/e5674022-efeb-11e6-8c30-a678897ce76c.png)

**Comment by davetimmins** [comment]
Thanks, yea I've seen this but haven't been able to reproduce it consistently. Hopefully it's just something stupid in the demo code

**Comment by davetimmins** [comment]
Looks to be fixed. I reworked the layer load check and also made the legend init each layer as and when they're ready rather than waiting for the entire map to be loaded. Mor erobust especially for maps that have dodgy layers in them e.g. https://davetimmins.com/arcgis-react-redux-legend/?webmap=8e42e164d4174da09f61fe0d3f206641

**Comment by tomwayson** [comment]
nice work!

So, is it just me, or is it not possible to use the legend turn off the Bike Paths layer on that map? (In latest Chrome) I click on the "eye"con, and it seems like the layer is still visible. Works for all the other layers, just not that one.

**Comment by davetimmins** [comment]
Yea there's an issue with that one, haven't dug into it yet but seems to be caused by that web map having another layer in it that is broken.

**Comment by davetimmins** [comment]
Fixed that layer issue with #6
